name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: github-user-actions/snk@v1
        with:
          github_user_name: NehaamKhan
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-light
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
